### ISSUE TITLE
add branch

### ISSUE THREAD

**Issue by rreppenhagen** [githubteacher/foundations-2015-06-04#139]
where are the steps to add a branch

**Comment by rreppenhagen** [comment]
do i add a file by using the "+" after the master?

**Comment by crichID** [comment]
you create the branch by clicking the dropdown next to master. Then you create the file by clicking the + next to the repo name

![screen shot 2015-06-04 at 1 09 08 pm](https://cloud.githubusercontent.com/assets/9950121/7989897/fd3820e4-0aba-11e5-8ed0-cecddf6dc8dd.png)
