### ISSUE TITLE
how can I move a file to another directory?

### ISSUE THREAD

**Issue by peterlubs** [githubteacher/foundations-2015-06-04#151]
how can I move a file to a directory like into the bio folder?

**Comment by rreppenhagen** [comment]
i have the same question

**Comment by gregbaxter** [comment]
:+1: 

great q

**Comment by staylor12** [comment]
In GitHub, edit the file. When editing, modify the breadcrumb path at the top. You can add directories by putting "/dirname/" in the filename input.

**Comment by githubstudent** [comment]
@staylor12 Thanks for answering on our behalf!
