### ISSUE TITLE
How do we delete a branch?

### ISSUE THREAD

**Issue by laurakellie** [githubteacher/foundations-2015-06-04#165]

**Comment by lwdupont** [comment]
Ya, I was wondering that too. I didn't delete after merge, and I don't see a way to do it when I'm sitting on my branch in the web UI.

**Comment by crichID** [comment]
@laurakellie @lwdupont you can delete your branch by going back to your merged pull request. The option to delete the branch will still be shown.

**Comment by laurakellie** [comment]
@crichID, got it - thanks!
