### ISSUE TITLE
How to update latest version

### ISSUE THREAD

**Issue by ManishVerma2805** [githubteacher/foundations-2015-06-04#175]

**Comment by githubstudent** [comment]
@ManishVerma2805 What version do you have, and what platform are you on?

**Comment by ManishVerma2805** [comment]
git version 1.9.5 (Apple Git-50.3)
Mac OS 10.9.5

**Comment by githubstudent** [comment]
@ManishVerma2805 That should be new enough for today, but you can get the latest release here: 
http://git-scm.com/downloads
