### ISSUE TITLE
config commands

### ISSUE THREAD

**Issue by pandeysk** [githubteacher/foundations-2015-06-04#177]
Can you please paste all the config commands you just executed?

**Comment by shmitr** [comment]
agree...I missed a couple.

**Comment by staylor12** [comment]
Here's everything from my history:
git config --global user.name "Scott Taylor"
git config --global user.name
git config --global user.email "Scott_Taylor@intuit.com"
git config --global user.email
git config --global core.editor "subl -n -w"
git config --global core.autocrlf input
git config --global push.default simple
git config --global --list

**Comment by pandeysk** [comment]
Thanx

**Comment by crichID** [comment]
@staylor12 :sparkles:
