### ISSUE TITLE
Cannot push from local 

### ISSUE THREAD

**Issue by JasonDe** [githubteacher/foundations-2015-06-04#186]
when I try to push from local I get the following error:

remote: Permission to githubteacher/foundations-2015-06-04.git denied to e60fdfa2baef26946f58fd5c7ae8a1f4eb3e718d.
fatal: unable to access 'https://github.com/githubteacher/foundations-2015-06-04.git/': The requested URL returned error
: 403

**Comment by githubstudent** [comment]
@JasonDe Ah, you're not a collaborator (so you don't have write access). Let me change that...
