### ISSUE TITLE
Add markholmberg bio 

### ISSUE THREAD

**Issue by maholmberg** [githubteacher/foundations-2015-06-04#49]
## My Bio!

-I am from San Diego, Ca
-I enjoy playing the piano

[]test
[]test2

@githubteacher here is my bio

**Comment by lwdupont** [comment]
You enjoy the pian ? ;-)

**Comment by maholmberg** [comment]
Good catch!

**Comment by lwdupont** [comment]
Live updates, that's cool.

**Comment by maholmberg** [comment]
Wasn't the [] supposed to do something?
