### ISSUE TITLE
How do i not get spammed by emails generated from this training?

### ISSUE THREAD

**Issue by pbaldwin71** [githubteacher/foundations-2015-06-04#8]
thank you

**Comment by lwdupont** [comment]
Click on the unsubscribe button to the left, pretty sure that will remove you from the emails.

**Comment by githubstudent** [comment]
@pbaldwin71 We'll go over this shortly!

**Comment by githubstudent** [comment]
There's more documentation on notifications [here](https://help.github.com/categories/notifications/).
